# Generated by Django 3.2.11 on 2022-02-10 04:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OfficeName', models.CharField(help_text='Office name', max_length=100, verbose_name='Office')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(help_text='Nombre comercial', max_length=50, verbose_name='Nombre')),
                ('TaxPayerID', models.CharField(blank=True, help_text='RFC', max_length=13, verbose_name='RFC')),
                ('TradeName', models.CharField(help_text='Razón Social de la empresa', max_length=50, verbose_name='Razón Social')),
                ('Slogan', models.CharField(blank=True, default='', help_text='Eslogan', max_length=50, verbose_name='Eslogan')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BirthDate', models.DateField(blank=True, null=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Name', max_length=200)),
                ('LastName', models.CharField(blank=True, default='', help_text='LastName', max_length=200)),
                ('DisplayName', models.CharField(blank=True, default='', help_text='Firstname', max_length=200, null=True)),
                ('RFC', models.CharField(blank=True, default='', help_text='RFC', max_length=13, null=True)),
                ('CURP', models.CharField(blank=True, default='', help_text='CURP', max_length=18, null=True)),
                ('JobTittle', models.CharField(blank=True, help_text='Job tittle', max_length=50, null=True)),
                ('CompanyEmail', models.EmailField(max_length=200, verbose_name='Office Email')),
                ('PersonalEmail', models.EmailField(blank=True, max_length=30, null=True, verbose_name='Personal Email')),
                ('PhoneNumber', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('Office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.office')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
