# Generated by Django 3.2.11 on 2023-05-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='APISecret',
            field=models.CharField(blank=True, default='', help_text='Secret', max_length=20, verbose_name='API Secret'),
        ),
    ]
