# Generated by Django 3.2.11 on 2023-05-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_userprofile_apisecret'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Token',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Token'),
        ),
    ]
