# Generated by Django 3.2.11 on 2022-02-16 08:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='MotorSerialNumber',
            new_name='EngineSerialNumber',
        ),
        migrations.AddField(
            model_name='driver',
            name='Comments',
            field=models.CharField(blank=True, default='', help_text='Comentarios sobre el conductor', max_length=300, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='driver',
            name='Employ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.employ'),
        ),
        migrations.AddField(
            model_name='issue',
            name='Date',
            field=models.DateField(default=datetime.datetime.now, help_text='Fecha del Evento', verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='issue',
            name='Description',
            field=models.CharField(blank=True, help_text='Descripción del evento', max_length=100, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='issue',
            name='Driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.driver'),
        ),
        migrations.AddField(
            model_name='issue',
            name='Time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, help_text='Hora del evento', verbose_name='Hora'),
        ),
        migrations.AddField(
            model_name='issue',
            name='Type',
            field=models.SmallIntegerField(choices=[(1, 'Itinerario de Viaje'), (2, 'Suministro de Combustible'), (3, 'Suministro interno'), (4, 'Mantenimiento'), (5, 'Hecho de transito')], default=1, help_text='Tipo de evento', null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='issue',
            name='Vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='issue',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleclasification',
            name='Code',
            field=models.CharField(help_text='Clave', max_length=20, null=True, verbose_name='Clave'),
        ),
    ]
