# Generated by Django 3.2.11 on 2022-02-17 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_auto_20220217_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Supplie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SupplieName', models.CharField(help_text='Nombre del suministro', max_length=30, verbose_name='Nombre')),
                ('Description', models.CharField(help_text='Descripción del articulo', max_length=30, verbose_name='Descripción')),
                ('Stock', models.SmallIntegerField(help_text='Unidades disponibles', verbose_name='Existencias')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveSmallIntegerField(help_text='Unidades disponibles', verbose_name='Existencias')),
                ('Event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.event')),
                ('Supplie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.supplie')),
            ],
        ),
        migrations.DeleteModel(
            name='InternalSupply',
        ),
        migrations.AddField(
            model_name='fuelsupply',
            name='Comments',
            field=models.CharField(help_text='Comentarios / Referencia', max_length=300, null=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='fuelsupply',
            name='CostPerUnit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo por unidad', max_digits=6, verbose_name='Costo por unidad'),
        ),
        migrations.AddField(
            model_name='fuelsupply',
            name='Event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.event'),
        ),
        migrations.AddField(
            model_name='fuelsupply',
            name='GaugeFuel',
            field=models.PositiveSmallIntegerField(default=0, help_text='Porcentaje de combustible en el Tanque', verbose_name='Indicador de combustible'),
        ),
        migrations.AddField(
            model_name='fuelsupply',
            name='Odometer',
            field=models.PositiveIntegerField(default=0, help_text='Medición del odometro', verbose_name='Indicador de recorrido.'),
        ),
        migrations.AddField(
            model_name='fuelsupply',
            name='Quantity',
            field=models.PositiveSmallIntegerField(default=0, help_text='Unidades disponibles', verbose_name='Existencias'),
        ),
        migrations.AddField(
            model_name='fuelsupply',
            name='Type',
            field=models.SmallIntegerField(choices=[(1, 'Gasolina'), (2, 'Diesel')], default=1, help_text='Tipo de combustible', verbose_name='Tipo de Combustible'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='FuelType',
            field=models.SmallIntegerField(choices=[(1, 'Gasolina'), (2, 'Diesel')], default=1, help_text='Tipo de combustible', verbose_name='Tipo de Combustible'),
        ),
    ]
