# Generated by Django 3.2.11 on 2022-02-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_auto_20220217_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplie',
            name='CostPerUnit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo por unidad', max_digits=6, verbose_name='Costo por unidad'),
        ),
        migrations.AddField(
            model_name='supply',
            name='Cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo', max_digits=6, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='Quantity',
            field=models.PositiveSmallIntegerField(help_text='Cantidad', verbose_name='Cantidad'),
        ),
    ]
