# Generated by Django 3.2.11 on 2022-03-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_fuelconsumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='TankCapacity',
            field=models.PositiveIntegerField(help_text='Capacidad del tanque de combustible', null=True, verbose_name='Capacidad del tanque'),
        ),
    ]
