# Generated by Django 3.2.11 on 2022-03-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_vehicle_tankcapacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelconsumption',
            old_name='FinalTravelReading',
            new_name='FinalTraveledReading',
        ),
        migrations.RenameField(
            model_name='fuelconsumption',
            old_name='InitialTravelReading',
            new_name='InitialTraveledReading',
        ),
    ]
