# Generated by Django 3.2.11 on 2022-03-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_auto_20220303_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelconsumption',
            name='EndDate',
            field=models.DateField(help_text='Final de medición', null=True, verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='FinalTraveledReading',
            field=models.PositiveIntegerField(help_text='Lectura final del odometro', null=True, verbose_name='Lectura final'),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='FuelEfficiency',
            field=models.DecimalField(decimal_places=2, help_text='Rendimiento del combustible', max_digits=8, null=True, verbose_name='Eficiencia'),
        ),
    ]
