# Generated by Django 3.2.11 on 2022-03-08 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0011_auto_20220303_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.SmallIntegerField(choices=[(1, 'Itinerario de Viaje'), (2, 'Suministro de Combustible'), (3, 'Suministro interno'), (4, 'Mantenimiento'), (5, 'Hecho de transito'), (6, 'Reporte de Falla'), (7, 'Asignación')], default=1, help_text='Tipo de evento', null=True, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('Driver', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.driver')),
                ('Vehicle', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FuelReading', models.PositiveSmallIntegerField(default=0, help_text='Porcentaje de combustible en el Tanque', verbose_name='Indicador de combustible')),
                ('TraveledReading', models.PositiveIntegerField(default=0, help_text='Medición del odometro', verbose_name='Indicador de recorrido.')),
                ('Comments', models.TextField(help_text='Comentarios / observaciones', max_length=100, verbose_name='Comentarios')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('Driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.driver')),
                ('Event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.event')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
