# Generated by Django 3.2.11 on 2022-03-15 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_auto_20220308_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Comments',
            field=models.CharField(help_text='Comentarios / observaciones', max_length=300, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.driver', verbose_name='Conductor asignado'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.driver', verbose_name='Conductor'),
        ),
        migrations.AlterField(
            model_name='state',
            name='Driver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='his_driver', to='fleet.driver', verbose_name='Conductor asignado'),
        ),
    ]
