# Generated by Django 3.2.11 on 2022-03-15 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0013_auto_20220315_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='created_by',
            new_name='update_by',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='created_on',
            new_name='update_on',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='created_by',
            new_name='update_by',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='created_on',
            new_name='update_on',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='created_by',
            new_name='update_by',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='created_on',
            new_name='update_on',
        ),
        migrations.AddField(
            model_name='fuelsupply',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuelsupply',
            name='update_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trafficincident',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trafficincident',
            name='update_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='update_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
