# Generated by Django 3.2.11 on 2022-05-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_auto_20220511_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='FuelType',
            field=models.SmallIntegerField(choices=[(1, 'Gasolina'), (2, 'Diesel')], default=1, help_text='Tipo de combustible', verbose_name='Tipo'),
        ),
    ]
