# Generated by Django 3.2.11 on 2023-03-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('location', models.CharField(max_length=400, verbose_name='Ubicaciòn')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(verbose_name='Desde')),
                ('end', models.DateField(verbose_name='Hasta:')),
                ('priority', models.SmallIntegerField(choices=[(1, 'Ugente'), (2, 'Alta'), (3, 'Normal')])),
            ],
        ),
    ]
