# Generated by Django 3.2.11 on 2023-03-27 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest', to='appointments.appointment'),
        ),
    ]
