# Generated by Django 3.2.11 on 2023-03-27 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_guest_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='appointment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='appointments.appointment'),
        ),
    ]
