# Generated by Django 3.2.11 on 2023-03-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_schedule_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='employ_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de empleado'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='employ_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='employ_title',
            field=models.CharField(max_length=30, null=True, verbose_name='Puesto'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end',
            field=models.DateTimeField(null=True, verbose_name='Hora fin:'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.SmallIntegerField(choices=[(1, 'Ugente'), (2, 'Alta'), (3, 'Normal')], null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(null=True, verbose_name='Hora de Inicio'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
