# Generated by Django 3.2.11 on 2023-03-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_auto_20230328_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name_plural': 'appointments'},
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='appointments_data',
        ),
    ]
