# Generated by Django 3.2.11 on 2023-03-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_auto_20230328_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
